/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PostCodeComponent {
    'required': boolean;
  }
  interface PostCodeComponentAttributes extends StencilHTMLAttributes {
    'required'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PostCodeComponent': Components.PostCodeComponent;
  }

  interface StencilIntrinsicElements {
    'post-code-component': Components.PostCodeComponentAttributes;
  }


  interface HTMLPostCodeComponentElement extends Components.PostCodeComponent, HTMLStencilElement {}
  var HTMLPostCodeComponentElement: {
    prototype: HTMLPostCodeComponentElement;
    new (): HTMLPostCodeComponentElement;
  };

  interface HTMLElementTagNameMap {
    'post-code-component': HTMLPostCodeComponentElement
  }

  interface ElementTagNameMap {
    'post-code-component': HTMLPostCodeComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
